module.exports = function (gulp, plugins, vars) {
	return function () {

		var d = plugins.q.defer();
		var fs = require('fs');
		var bowerJson = {
			_comment: 'THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.',
			name: vars.pkg.name,
			version: vars.pkg.version,
			description: vars.pkg.description,
			ignore: [
				".DS_Store",
				".git",
				".gitignore",
				"node_modules",
				"bower_components",
				".sass-cache",
				"npm-debug.log"
			],
			dependencies: vars.pkg.bower
		};

		bowerJson = JSON.stringify(bowerJson, null, '\t')

		fs.writeFile('./bower.json', bowerJson, function() {
			d.resolve(true);
		});

		return d.promise;
	};
};
